// plugingen 生成 cmd/marketplace_plugins.go：扫描 custom/plugins/*/plugin.json，
// 为每个市场插件生成 import 与 AddPlugin 注册调用。
//
// 用法：go run ./tools/plugingen （在仓库根目录执行；插件市场安装流水线会自动调用）。
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jeanhua/AniaBot/common/pluginmeta"
)

const (
	outputPath = "cmd/marketplace_plugins.go"
	header     = `// Code generated by plugingen (go run ./tools/plugingen). DO NOT EDIT.
//
// 本文件由插件市场安装/卸载流水线自动重写：扫描 custom/plugins/*/plugin.json，
// 为每个已安装插件生成 import 与 AddPlugin 注册调用。内置插件注册在 cmd/main.go，
// 与市场插件互不影响。

package main

import (
	"github.com/jeanhua/AniaBot/bot/core"
`
	footer = `)

// registerMarketplacePlugins 注册插件市场安装的第三方插件。
func registerMarketplacePlugins(ania *core.AniaBot) {
`
)

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, "plugingen:", err)
		os.Exit(1)
	}
	plugins, err := collectPlugins(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "plugingen:", err)
		os.Exit(1)
	}
	if err := writeRegistry(root, plugins); err != nil {
		fmt.Fprintln(os.Stderr, "plugingen:", err)
		os.Exit(1)
	}
	fmt.Printf("plugingen: 已生成 %s，共 %d 个市场插件\n", filepath.Join(root, outputPath), len(plugins))
}

// findModuleRoot 向上查找包含 AniaBot 主模块的 go.mod 的目录。
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil && strings.Contains(string(data), "module "+pluginmeta.ModulePath) {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("未找到 AniaBot 主模块（向上查找 go.mod 失败）")
		}
		dir = parent
	}
}

// collectPlugins 扫描 custom/plugins/*/plugin.json 并按 ID 排序返回校验通过的元信息。
func collectPlugins(root string) ([]*pluginmeta.Manifest, error) {
	dir := filepath.Join(root, pluginmeta.PluginRoot)
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("读取 %s 失败: %w", dir, err)
	}
	var out []*pluginmeta.Manifest
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		manifestPath := filepath.Join(dir, e.Name(), "plugin.json")
		if _, err := os.Stat(manifestPath); err != nil {
			continue // 非市场插件目录（无 plugin.json）直接跳过
		}
		m, err := pluginmeta.LoadManifest(manifestPath)
		if err != nil {
			return nil, fmt.Errorf("插件 %s 元信息非法: %w", e.Name(), err)
		}
		if m.ID != e.Name() {
			return nil, fmt.Errorf("插件目录 %s 与 plugin.json 的 id %q 不一致", e.Name(), m.ID)
		}
		out = append(out, m)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// writeRegistry 写出（或覆盖）注册文件；无插件时生成仅含空函数的占位文件，
// 保证全新克隆也能直接编译。
func writeRegistry(root string, plugins []*pluginmeta.Manifest) error {
	var b strings.Builder
	b.WriteString(header)
	for _, m := range plugins {
		fmt.Fprintf(&b, "\tplug_%s %q\n", alias(m.ID), pluginmeta.ImportPath(m.ID))
	}
	b.WriteString(footer)
	for _, m := range plugins {
		fmt.Fprintf(&b, "\tania.AddPlugin(plug_%s.%s())\n", alias(m.ID), m.Constructor())
	}
	b.WriteString("}\n")

	path := filepath.Join(root, outputPath)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// alias 生成 import 别名：ID 中的 - 替换为 _，避免与关键字冲突。
func alias(id string) string {
	return strings.ReplaceAll(id, "-", "_")
}
