// Code generated by plugingen (go run ./tools/plugingen). DO NOT EDIT.
//
// 本文件由插件市场安装/卸载流水线自动重写：扫描 custom/plugins/*/plugin.json，
// 为每个已安装插件生成 import 与 AddPlugin 注册调用。内置插件注册在 cmd/main.go，
// 与市场插件互不影响。

package main

import (
	"github.com/jeanhua/AniaBot/bot/core"
)

// registerMarketplacePlugins 注册插件市场安装的第三方插件。
func registerMarketplacePlugins(ania *core.AniaBot) {
}
